const {
  _,
  Xterm,
  GFormSelect,
  Blink,
  HalfResizeForTwoHorizontal,
  GEditor,
  OperationPanel,
  BluePrintPopover,
  Mobx,
  MobxReact,
  HalfResizeForTwo,
  MobxReactLite,
  ProgressBar,
  Dialog,
  Tag,
  Popover,
  Radio,
  ButtonGroup,
  TextArea,
  Intent,
  observer,
  Position,
  Toaster,
  Checkbox,
  ContextMenu,
  NumericInput,
  FormGroup,
  HTMLSelect,
  ControlGroup,
  InputGroup,
  Navbar,
  NavbarHeading,
  NonIdealState,
  NavbarDivider,
  NavbarGroup,
  Alignment,
  Classes,
  Tree,
  Icon,
  Card,
  Elevation,
  Button,
  PanelStack2,
  Spinner,
  Callout,
  PanelStack,
  gstore,
  AnchorButton,
  Tooltip,
  Drawer,
  Overlay,
  Alert,
  RadioGroup,
  Menu,
  MenuItem,
  MenuDivider,
  BluePrintTable,
  autorun,
  ColumnHeaderCell,
  Cell,
  Column,
  Table,
  Regions,
  BluePrintDocs,
  BluePrintCpt,
  observable,
  gutils,
  ReactDOM,
  
  useEffect,
  useCallback,
  useContext,
  useMemo,
  useState,
  useAsObservableSource,
  useLocalStore,
  useObserver,
  Provider,
  Router,
  inject,
  Html_select,
  BeautifyCodeCommon,
  prettier,
  xmlutils,
  createHistory,
  withRouter,
  Switch,
  Route,
  Link,
  useHistory,
} = window.CodeGenDefinition;

let SQLHistoryView = observer((props) => {
  let { PUtils } = props;
  let { crtModel } = PUtils;
  return PUtils.jsx.createPanelWithBtnControls({
    // fn_get_copy_result: async () => {
    //   return PUtils.editor.getValue({
    //     id: "sql_drafts__encode_text_result",
    //   });
    // },
    helpBtnProps: {
      minimal: true,
      outlined: true,
    },
    controls: [
      {
        text: t(`Back to Console`),
        intent: "none",
        minimal: true,
        outlined: true,
        loading_id: "encode_sql_drafts__cancel",
        onClick: async () => {
          //
          PUtils.crtModel.view_type = "main";
        },
      },
    ],
    rightControls: [
      {
        text: t(`Clean History`),
        intent: "danger",
        minimal: true,
        outlined: true,
        icon: "trash",
        //
        onClick: () => {
          // identify
        },
      },
    ],
    body: <div className="w100 h100">history view</div>,
  });
});

export default SQLHistoryView;
