const {
  _,
  Xterm,
  GFormSelect,
  Blink,
  HalfResizeForTwoHorizontal,
  GEditor,
  OperationPanel,
  BluePrintPopover,
  Mobx,
  MobxReact,
  HalfResizeForTwo,
  MobxReactLite,
  ProgressBar,
  Dialog,
  Tag,
  Popover,
  Radio,
  ButtonGroup,
  TextArea,
  Intent,
  observer,
  Position,
  Toaster,
  Checkbox,
  ContextMenu,
  NumericInput,
  FormGroup,
  HTMLSelect,
  ControlGroup,
  InputGroup,
  Navbar,
  NavbarHeading,
  NonIdealState,
  NavbarDivider,
  NavbarGroup,
  Alignment,
  Classes,
  Tree,
  Icon,
  Card,
  Elevation,
  Button,
  PanelStack2,
  Spinner,
  Callout,
  PanelStack,
  gstore,
  AnchorButton,
  Tooltip,
  Drawer,
  Overlay,
  Alert,
  RadioGroup,
  Menu,
  MenuItem,
  MenuDivider,
  BluePrintTable,
  autorun,
  ColumnHeaderCell,
  Cell,
  Column,
  Table,
  Regions,
  BluePrintDocs,
  BluePrintCpt,
  observable,
  gutils,
  ReactDOM,
  
  useEffect,
  useCallback,
  useContext,
  useMemo,
  useState,
  useAsObservableSource,
  useLocalStore,
  useObserver,
  Provider,
  Router,
  inject,
  Html_select,
  BeautifyCodeCommon,
  prettier,
  xmlutils,
  createHistory,
  withRouter,
  Switch,
  Route,
  Link,
  useHistory,
} = window.CodeGenDefinition;

let fn_newDbConfig = () => {
  return {
    url_params_mysql: `?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8`,
    url_params_mariadb: `?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8`,
    url_params_sqlite: ``,
    url_params_h2: ``,
    url_params_postgresql: ``,
    url_params_mssql: ``,
    url_params_oracle: ``,
    connectionType: "general",
    configId: gutils.uuid(),
    dbType: "mysql",
    customTestQuerySQL: null,
    customJDBCUrl: null,
    username: null,
    password: null,
    queryTimeout: 0,
    executeTimeout: 0,
    driverClazzName: null,
    driverFilePath: null,
    config: null,
    extMap: {},
    connectTimeout: 5000,
    displayMode: `visual`,
  };
};

let fn_initialState = async () => {
  let default_config_value = [
    `url=jdbc:mysql://127.0.0.1:3306/social`,
    `username="root"`,
    `password="test100"`,
  ].join("\n");
  return {
    needNewEdit: true,
    uid: gutils.uuid(),
    view_type: "add",
    created: false,
    tmp_dbconfig: fn_newDbConfig(),
    dbconfig: fn_newDbConfig(),
    // increase
    increase_editor_num: 1,
    titleMsg: null,
    // editors
    allSQLEditors: [],
    conn_status_loading: false,
    crtConnectionStatus: {
      runningUserInstruction: false,
      closed: false,
      createHourTimeStr: "2022-08-01 10:01:30",
    },
    retrieveDefinitions: [],
    crtSQLResultId: null,
    activeSQLConnId: null,
    jdbcRawConfig: default_config_value,
    tmpJdbcRawConfig: default_config_value,
  };
};
export default fn_initialState;
