const {
  _,
  Xterm,
  GFormSelect,
  Blink,
  HalfResizeForTwoHorizontal,
  GEditor,
  OperationPanel,
  BluePrintPopover,
  Mobx,
  MobxReact,
  HalfResizeForTwo,
  MobxReactLite,
  ProgressBar,
  Dialog,
  Tag,
  Popover,
  Radio,
  ButtonGroup,
  TextArea,
  Intent,
  observer,
  Position,
  Toaster,
  Checkbox,
  ContextMenu,
  NumericInput,
  FormGroup,
  HTMLSelect,
  ControlGroup,
  InputGroup,
  Navbar,
  NavbarHeading,
  NonIdealState,
  NavbarDivider,
  NavbarGroup,
  Alignment,
  Classes,
  Tree,
  Icon,
  Card,
  Elevation,
  Button,
  PanelStack2,
  Spinner,
  Callout,
  PanelStack,
  gstore,
  AnchorButton,
  Tooltip,
  Drawer,
  Overlay,
  Alert,
  RadioGroup,
  Menu,
  MenuItem,
  MenuDivider,
  BluePrintTable,
  autorun,
  ColumnHeaderCell,
  Cell,
  Column,
  Table,
  Regions,
  BluePrintDocs,
  BluePrintCpt,
  observable,
  gutils,
  ReactDOM,
  
  useEffect,
  useCallback,
  useContext,
  useMemo,
  useState,
  useAsObservableSource,
  useLocalStore,
  useObserver,
  Provider,
  Router,
  inject,
  Html_select,
  BeautifyCodeCommon,
  prettier,
  xmlutils,
  createHistory,
  withRouter,
  Switch,
  Route,
  Link,
  useHistory,
} = window.CodeGenDefinition;

import MainSQLView from "./Common_MainSQLView";
import ModifyConfigView from "./Common_ModifyConfigView";
import SQLHistoryView from "./Common_SQLHistoryView";

const WrapRootEntryView = observer((props) => {
  let { PUtils } = props;
  let { crtModel } = PUtils;
  const viewObj = {
    main: <MainSQLView PUtils={props.PUtils} />,
    add: <ModifyConfigView PUtils={props.PUtils} />,
    modify: <ModifyConfigView PUtils={props.PUtils} />,
    create: <ModifyConfigView PUtils={props.PUtils} />,
    history: <SQLHistoryView PUtils={props.PUtils} />,
  };
  let cpt = viewObj[crtModel.view_type];
  if (_.isNil(cpt)) {
    cpt = <div>Loading...</div>;
  }
  return cpt;
});

export default WrapRootEntryView;
