// Date: Sun, 14 Jan 2024
// Second Author: Ryan Laf
// Description:
// License: AGPLv3
// Copyright (C) 2024 - Present, https://laftools.dev and https://codegen.cc

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
 *
 * @author n1474335 [n1474335@gmail.com]
 * @copyright Crown Copyright 2023
 * @license Apache-2.0
 */
import Bzip2Compress from "../../operations/Bzip2Compress.mjs";
import Bzip2Decompress from "../../operations/Bzip2Decompress.mjs";
import Gunzip from "../../operations/Gunzip.mjs";
import Gzip from "../../operations/Gzip.mjs";
import LZ4Compress from "../../operations/LZ4Compress.mjs";
import LZ4Decompress from "../../operations/LZ4Decompress.mjs";
import LZMACompress from "../../operations/LZMACompress.mjs";
import LZMADecompress from "../../operations/LZMADecompress.mjs";
import LZStringCompress from "../../operations/LZStringCompress.mjs";
import LZStringDecompress from "../../operations/LZStringDecompress.mjs";
import RawDeflate from "../../operations/RawDeflate.mjs";
import RawInflate from "../../operations/RawInflate.mjs";
import Tar from "../../operations/Tar.mjs";
import Untar from "../../operations/Untar.mjs";
import Unzip from "../../operations/Unzip.mjs";
import Zip from "../../operations/Zip.mjs";
import ZlibDeflate from "../../operations/ZlibDeflate.mjs";
import ZlibInflate from "../../operations/ZlibInflate.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Compression = {
  "Bzip2 Compress": Bzip2Compress,
  "Bzip2 Decompress": Bzip2Decompress,
  Gunzip: Gunzip,
  Gzip: Gzip,
  "LZ4 Compress": LZ4Compress,
  "LZ4 Decompress": LZ4Decompress,
  "LZMA Compress": LZMACompress,
  "LZMA Decompress": LZMADecompress,
  "LZString Compress": LZStringCompress,
  "LZString Decompress": LZStringDecompress,
  "Raw Deflate": RawDeflate,
  "Raw Inflate": RawInflate,
  Tar: Tar,
  Untar: Untar,
  Unzip: Unzip,
  Zip: Zip,
  "Zlib Deflate": ZlibDeflate,
  "Zlib Inflate": ZlibInflate,
};

export default OpModules;
