// LafTools
// 
// Date: Sun, 14 Jan 2024
// Second Author: Ryan Laf 
// Description: 
// License: AGPLv3
// Copyright (C) 2024 - Present, https://laftools.dev and https://codegen.cc

/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2023
* @license Apache-2.0
*/
// import ADD from "../../operations/ADD.mjs";
// import AND from "../../operations/AND.mjs";
// import AddLineNumbers from "../../operations/AddLineNumbers.mjs";
// import BaconCipherDecode from "../../operations/BaconCipherDecode.mjs";
// import BaconCipherEncode from "../../operations/BaconCipherEncode.mjs";
// import BitShiftLeft from "../../operations/BitShiftLeft.mjs";
// import BitShiftRight from "../../operations/BitShiftRight.mjs";
// import CSVToJSON from "../../operations/CSVToJSON.mjs";
// import CartesianProduct from "../../operations/CartesianProduct.mjs";
// import ChaCha from "../../operations/ChaCha.mjs";
// import ChangeIPFormat from "../../operations/ChangeIPFormat.mjs";
// import ChiSquare from "../../operations/ChiSquare.mjs";
// import Comment from "../../operations/Comment.mjs";
// import ConditionalJump from "../../operations/ConditionalJump.mjs";
// import ConvertArea from "../../operations/ConvertArea.mjs";
// import ConvertDataUnits from "../../operations/ConvertDataUnits.mjs";
// import ConvertDistance from "../../operations/ConvertDistance.mjs";
// import ConvertMass from "../../operations/ConvertMass.mjs";
// import ConvertSpeed from "../../operations/ConvertSpeed.mjs";
// import ConvertToNATOAlphabet from "../../operations/ConvertToNATOAlphabet.mjs";
// import CountOccurrences from "../../operations/CountOccurrences.mjs";
// import DNSOverHTTPS from "../../operations/DNSOverHTTPS.mjs";
// import DechunkHTTPResponse from "../../operations/DechunkHTTPResponse.mjs";
// import DecodeNetBIOSName from "../../operations/DecodeNetBIOSName.mjs";
// import DefangIPAddresses from "../../operations/DefangIPAddresses.mjs";
// import DefangURL from "../../operations/DefangURL.mjs";
// import DetectFileType from "../../operations/DetectFileType.mjs";
// import Divide from "../../operations/Divide.mjs";
// import DropBytes from "../../operations/DropBytes.mjs";
// import ELFInfo from "../../operations/ELFInfo.mjs";
// import EncodeNetBIOSName from "../../operations/EncodeNetBIOSName.mjs";
// import EscapeString from "../../operations/EscapeString.mjs";
// import EscapeUnicodeCharacters from "../../operations/EscapeUnicodeCharacters.mjs";
// import ExpandAlphabetRange from "../../operations/ExpandAlphabetRange.mjs";
// import ExtractFiles from "../../operations/ExtractFiles.mjs";
// import ExtractID3 from "../../operations/ExtractID3.mjs";
// import Fork from "../../operations/Fork.mjs";
// import FormatMACAddresses from "../../operations/FormatMACAddresses.mjs";
// import FrequencyDistribution from "../../operations/FrequencyDistribution.mjs";
// import FromBCD from "../../operations/FromBCD.mjs";
// import FromBase from "../../operations/FromBase.mjs";
// import FromBase32 from "../../operations/FromBase32.mjs";
// import FromBase45 from "../../operations/FromBase45.mjs";
// import FromBase58 from "../../operations/FromBase58.mjs";
// import FromBase62 from "../../operations/FromBase62.mjs";
// import FromBase64 from "../../operations/FromBase64.mjs";
// import FromBase85 from "../../operations/FromBase85.mjs";
// import FromBinary from "../../operations/FromBinary.mjs";
// import FromBraille from "../../operations/FromBraille.mjs";
// import FromCaseInsensitiveRegex from "../../operations/FromCaseInsensitiveRegex.mjs";
// import FromCharcode from "../../operations/FromCharcode.mjs";
// import FromDecimal from "../../operations/FromDecimal.mjs";
// import FromHex from "../../operations/FromHex.mjs";
// import FromHexContent from "../../operations/FromHexContent.mjs";
// import FromHexdump from "../../operations/FromHexdump.mjs";
// import FromMorseCode from "../../operations/FromMorseCode.mjs";
// import FromOctal from "../../operations/FromOctal.mjs";
// import FromQuotedPrintable from "../../operations/FromQuotedPrintable.mjs";
// import FromUNIXTimestamp from "../../operations/FromUNIXTimestamp.mjs";
// import FuzzyMatch from "../../operations/FuzzyMatch.mjs";
// import GenerateDeBruijnSequence from "../../operations/GenerateDeBruijnSequence.mjs";
// import GenerateHOTP from "../../operations/GenerateHOTP.mjs";
// import GenerateLoremIpsum from "../../operations/GenerateLoremIpsum.mjs";
// import GenerateTOTP from "../../operations/GenerateTOTP.mjs";
// import GetAllCasings from "../../operations/GetAllCasings.mjs";
// import GetTime from "../../operations/GetTime.mjs";
// import GroupIPAddresses from "../../operations/GroupIPAddresses.mjs";
// import HTMLToText from "../../operations/HTMLToText.mjs";
// import HTTPRequest from "../../operations/HTTPRequest.mjs";
// import HammingDistance from "../../operations/HammingDistance.mjs";
// import HaversineDistance from "../../operations/HaversineDistance.mjs";
// import Head from "../../operations/Head.mjs";
// import IndexOfCoincidence from "../../operations/IndexOfCoincidence.mjs";
// import JSONToCSV from "../../operations/JSONToCSV.mjs";
// import Jump from "../../operations/Jump.mjs";
// import Label from "../../operations/Label.mjs";
// import LevenshteinDistance from "../../operations/LevenshteinDistance.mjs";
// import LuhnChecksum from "../../operations/LuhnChecksum.mjs";
// import Magic from "../../operations/Magic.mjs";
// import Mean from "../../operations/Mean.mjs";
// import Median from "../../operations/Median.mjs";
// import Merge from "../../operations/Merge.mjs";
// import MicrosoftScriptDecoder from "../../operations/MicrosoftScriptDecoder.mjs";
// import Multiply from "../../operations/Multiply.mjs";
// import NOT from "../../operations/NOT.mjs";
// import Numberwang from "../../operations/Numberwang.mjs";
// import OR from "../../operations/OR.mjs";
// import OffsetChecker from "../../operations/OffsetChecker.mjs";
// import PEMToHex from "../../operations/PEMToHex.mjs";
// import PHPDeserialize from "../../operations/PHPDeserialize.mjs";
// import PLISTViewer from "../../operations/PLISTViewer.mjs";
// import PadLines from "../../operations/PadLines.mjs";
// import ParseColourCode from "../../operations/ParseColourCode.mjs";
// import ParseDateTime from "../../operations/ParseDateTime.mjs";
// import ParseIPRange from "../../operations/ParseIPRange.mjs";
// import ParseIPv4Header from "../../operations/ParseIPv4Header.mjs";
// import ParseIPv6Address from "../../operations/ParseIPv6Address.mjs";
// import ParseSSHHostKey from "../../operations/ParseSSHHostKey.mjs";
// import ParseTCP from "../../operations/ParseTCP.mjs";
// import ParseTLV from "../../operations/ParseTLV.mjs";
// import ParseUDP from "../../operations/ParseUDP.mjs";
// import ParseUNIXFilePermissions from "../../operations/ParseUNIXFilePermissions.mjs";
// import PlayMedia from "../../operations/PlayMedia.mjs";
// import PowerSet from "../../operations/PowerSet.mjs";
// import ROT13 from "../../operations/ROT13.mjs";
// import ROT13BruteForce from "../../operations/ROT13BruteForce.mjs";
// import ROT47 from "../../operations/ROT47.mjs";
// import ROT47BruteForce from "../../operations/ROT47BruteForce.mjs";
// import ROT8000 from "../../operations/ROT8000.mjs";
// import RemoveDiacritics from "../../operations/RemoveDiacritics.mjs";
// import RemoveLineNumbers from "../../operations/RemoveLineNumbers.mjs";
// import RemoveNullBytes from "../../operations/RemoveNullBytes.mjs";
// import RemoveWhitespace from "../../operations/RemoveWhitespace.mjs";
// import Return from "../../operations/Return.mjs";
// import Reverse from "../../operations/Reverse.mjs";
// import RotateLeft from "../../operations/RotateLeft.mjs";
// import RotateRight from "../../operations/RotateRight.mjs";
// import SUB from "../../operations/SUB.mjs";
// import ScanForEmbeddedFiles from "../../operations/ScanForEmbeddedFiles.mjs";
// import SetDifference from "../../operations/SetDifference.mjs";
// import SetIntersection from "../../operations/SetIntersection.mjs";
// import SetUnion from "../../operations/SetUnion.mjs";
// import ShowBase64Offsets from "../../operations/ShowBase64Offsets.mjs";
// import Shuffle from "../../operations/Shuffle.mjs";
// import Sleep from "../../operations/Sleep.mjs";
// import Sort from "../../operations/Sort.mjs";
// import Split from "../../operations/Split.mjs";
// import StandardDeviation from "../../operations/StandardDeviation.mjs";
// import StripHTMLTags from "../../operations/StripHTMLTags.mjs";
// import StripHTTPHeaders from "../../operations/StripHTTPHeaders.mjs";
// import Subsection from "../../operations/Subsection.mjs";
// import Substitute from "../../operations/Substitute.mjs";
// import Subtract from "../../operations/Subtract.mjs";
// import Sum from "../../operations/Sum.mjs";
// import SwapCase from "../../operations/SwapCase.mjs";
// import SwapEndianness from "../../operations/SwapEndianness.mjs";
// import SymmetricDifference from "../../operations/SymmetricDifference.mjs";
// import Tail from "../../operations/Tail.mjs";
// import TakeBytes from "../../operations/TakeBytes.mjs";
// import ToBCD from "../../operations/ToBCD.mjs";
// import ToBase from "../../operations/ToBase.mjs";
// import ToBase32 from "../../operations/ToBase32.mjs";
// import ToBase45 from "../../operations/ToBase45.mjs";
// import ToBase58 from "../../operations/ToBase58.mjs";
// import ToBase62 from "../../operations/ToBase62.mjs";
// import ToBase64 from "../../operations/ToBase64.mjs";
// import ToBase85 from "../../operations/ToBase85.mjs";
// import ToBinary from "../../operations/ToBinary.mjs";
// import ToBraille from "../../operations/ToBraille.mjs";
// import ToCaseInsensitiveRegex from "../../operations/ToCaseInsensitiveRegex.mjs";
// import ToCharcode from "../../operations/ToCharcode.mjs";
// import ToDecimal from "../../operations/ToDecimal.mjs";
// import ToHex from "../../operations/ToHex.mjs";
// import ToHexContent from "../../operations/ToHexContent.mjs";
// import ToHexdump from "../../operations/ToHexdump.mjs";
// import ToLowerCase from "../../operations/ToLowerCase.mjs";
// import ToMorseCode from "../../operations/ToMorseCode.mjs";
// import ToOctal from "../../operations/ToOctal.mjs";
// import ToQuotedPrintable from "../../operations/ToQuotedPrintable.mjs";
// import ToTable from "../../operations/ToTable.mjs";
// import ToUNIXTimestamp from "../../operations/ToUNIXTimestamp.mjs";
// import ToUpperCase from "../../operations/ToUpperCase.mjs";
// import TranslateDateTimeFormat from "../../operations/TranslateDateTimeFormat.mjs";
// import UNIXTimestampToWindowsFiletime from "../../operations/UNIXTimestampToWindowsFiletime.mjs";
// import UnescapeString from "../../operations/UnescapeString.mjs";
// import UnescapeUnicodeCharacters from "../../operations/UnescapeUnicodeCharacters.mjs";
// import UnicodeTextFormat from "../../operations/UnicodeTextFormat.mjs";
// import Unique from "../../operations/Unique.mjs";
// import VarIntDecode from "../../operations/VarIntDecode.mjs";
// import VarIntEncode from "../../operations/VarIntEncode.mjs";
// import WindowsFiletimeToUNIXTimestamp from "../../operations/WindowsFiletimeToUNIXTimestamp.mjs";
// import XKCDRandomNumber from "../../operations/XKCDRandomNumber.mjs";
// import XOR from "../../operations/XOR.mjs";
// import XORBruteForce from "../../operations/XORBruteForce.mjs";

// const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

let definitions = {
    // "ADD": ADD,
    // "AND": AND,
    // "Add line numbers": AddLineNumbers,
    // "Bacon Cipher Decode": BaconCipherDecode,
    // "Bacon Cipher Encode": BaconCipherEncode,
    // "Bit shift left": BitShiftLeft,
    // "Bit shift right": BitShiftRight,
    // "CSV to JSON": CSVToJSON,
    // "Cartesian Product": CartesianProduct,
    // "ChaCha": ChaCha,
    // "Change IP format": ChangeIPFormat,
    // "Chi Square": ChiSquare,
    // "Comment": Comment,
    // "Conditional Jump": ConditionalJump,
    // "Convert area": ConvertArea,
    // "Convert data units": ConvertDataUnits,
    // "Convert distance": ConvertDistance,
    // "Convert mass": ConvertMass,
    // "Convert speed": ConvertSpeed,
    // "Convert to NATO alphabet": ConvertToNATOAlphabet,
    // "Count occurrences": CountOccurrences,
    // "DNS over HTTPS": DNSOverHTTPS,
    // "Dechunk HTTP response": DechunkHTTPResponse,
    // "Decode NetBIOS Name": DecodeNetBIOSName,
    // "Defang IP Addresses": DefangIPAddresses,
    // "Defang URL": DefangURL,
    // "Detect File Type": DetectFileType,
    // "Divide": Divide,
    // "Drop bytes": DropBytes,
    // "ELF Info": ELFInfo,
    // "Encode NetBIOS Name": EncodeNetBIOSName,
    // "Escape string": EscapeString,
    // "Escape Unicode Characters": EscapeUnicodeCharacters,
    // "Expand alphabet range": ExpandAlphabetRange,
    // "Extract Files": ExtractFiles,
    // "Extract ID3": ExtractID3,
    // "Fork": Fork,
    // "Format MAC addresses": FormatMACAddresses,
    // "Frequency distribution": FrequencyDistribution,
    // "From BCD": FromBCD,
    // "From Base": FromBase,
    // "From Base32": FromBase32,
    // "From Base45": FromBase45,
    // "From Base58": FromBase58,
    // "From Base62": FromBase62,
    // "From Base64": FromBase64,
    // "From Base85": FromBase85,
    // "From Binary": FromBinary,
    // "From Braille": FromBraille,
    // "From Case Insensitive Regex": FromCaseInsensitiveRegex,
    // "From Charcode": FromCharcode,
    // "From Decimal": FromDecimal,
    // "From Hex": FromHex,
    // "From Hex Content": FromHexContent,
    // "From Hexdump": FromHexdump,
    // "From Morse Code": FromMorseCode,
    // "From Octal": FromOctal,
    // "From Quoted Printable": FromQuotedPrintable,
    // "From UNIX Timestamp": FromUNIXTimestamp,
    // "Fuzzy Match": FuzzyMatch,
    // "Generate De Bruijn Sequence": GenerateDeBruijnSequence,
    // "Generate HOTP": GenerateHOTP,
    // "Generate Lorem Ipsum": GenerateLoremIpsum,
    // "Generate TOTP": GenerateTOTP,
    // "Get All Casings": GetAllCasings,
    // "Get Time": GetTime,
    // "Group IP addresses": GroupIPAddresses,
    // "HTML To Text": HTMLToText,
    // "HTTP request": HTTPRequest,
    // "Hamming Distance": HammingDistance,
    // "Haversine distance": HaversineDistance,
    // "Head": Head,
    // "Index of Coincidence": IndexOfCoincidence,
    // "JSON to CSV": JSONToCSV,
    // "Jump": Jump,
    // "Label": Label,
    // "Levenshtein Distance": LevenshteinDistance,
    // "Luhn Checksum": LuhnChecksum,
    // "Magic": Magic,
    // "Mean": Mean,
    // "Median": Median,
    // "Merge": Merge,
    // "Microsoft Script Decoder": MicrosoftScriptDecoder,
    // "Multiply": Multiply,
    // "NOT": NOT,
    // "Numberwang": Numberwang,
    // "OR": OR,
    // "Offset checker": OffsetChecker,
    // "PEM to Hex": PEMToHex,
    // "PHP Deserialize": PHPDeserialize,
    // "P-list Viewer": PLISTViewer,
    // "Pad lines": PadLines,
    // "Parse colour code": ParseColourCode,
    // "Parse DateTime": ParseDateTime,
    // "Parse IP range": ParseIPRange,
    // "Parse IPv4 header": ParseIPv4Header,
    // "Parse IPv6 address": ParseIPv6Address,
    // "Parse SSH Host Key": ParseSSHHostKey,
    // "Parse TCP": ParseTCP,
    // "Parse TLV": ParseTLV,
    // "Parse UDP": ParseUDP,
    // "Parse UNIX file permissions": ParseUNIXFilePermissions,
    // "Play Media": PlayMedia,
    // "Power Set": PowerSet,
    // "ROT13": ROT13,
    // "ROT13 Brute Force": ROT13BruteForce,
    // "ROT47": ROT47,
    // "ROT47 Brute Force": ROT47BruteForce,
    // "ROT8000": ROT8000,
    // "Remove Diacritics": RemoveDiacritics,
    // "Remove line numbers": RemoveLineNumbers,
    // "Remove null bytes": RemoveNullBytes,
    // "Remove whitespace": RemoveWhitespace,
    // "Return": Return,
    // "Reverse": Reverse,
    // "Rotate left": RotateLeft,
    // "Rotate right": RotateRight,
    // "SUB": SUB,
    // "Scan for Embedded Files": ScanForEmbeddedFiles,
    // "Set Difference": SetDifference,
    // "Set Intersection": SetIntersection,
    // "Set Union": SetUnion,
    // "Show Base64 offsets": ShowBase64Offsets,
    // "Shuffle": Shuffle,
    // "Sleep": Sleep,
    // "Sort": Sort,
    // "Split": Split,
    // "Standard Deviation": StandardDeviation,
    // "Strip HTML tags": StripHTMLTags,
    // "Strip HTTP headers": StripHTTPHeaders,
    // "Subsection": Subsection,
    // "Substitute": Substitute,
    // "Subtract": Subtract,
    // "Sum": Sum,
    // "Swap case": SwapCase,
    // "Swap endianness": SwapEndianness,
    // "Symmetric Difference": SymmetricDifference,
    // "Tail": Tail,
    // "Take bytes": TakeBytes,
    // "To BCD": ToBCD,
    // "To Base": ToBase,
    // "To Base32": ToBase32,
    // "To Base45": ToBase45,
    // "To Base58": ToBase58,
    // "To Base62": ToBase62,
    // "ToBase64": ToBase64,
    // "To Base85": ToBase85,
    // "To Binary": ToBinary,
    // "To Braille": ToBraille,
    // "To Case Insensitive Regex": ToCaseInsensitiveRegex,
    // "To Charcode": ToCharcode,
    // "To Decimal": ToDecimal,
    // "To Hex": ToHex,
    // "To Hex Content": ToHexContent,
    // "To Hexdump": ToHexdump,
    // "To Lower case": ToLowerCase,
    // "To Morse Code": ToMorseCode,
    // "To Octal": ToOctal,
    // "To Quoted Printable": ToQuotedPrintable,
    // "To Table": ToTable,
    // "To UNIX Timestamp": ToUNIXTimestamp,
    // "To Upper case": ToUpperCase,
    // "Translate DateTime Format": TranslateDateTimeFormat,
    // "UNIX Timestamp to Windows Filetime": UNIXTimestampToWindowsFiletime,
    // "Unescape string": UnescapeString,
    // "Unescape Unicode Characters": UnescapeUnicodeCharacters,
    // "Unicode Text Format": UnicodeTextFormat,
    // "Unique": Unique,
    // "VarInt Decode": VarIntDecode,
    // "VarInt Encode": VarIntEncode,
    // "Windows Filetime to UNIX Timestamp": WindowsFiletimeToUNIXTimestamp,
    // "XKCD Random Number": XKCDRandomNumber,
    // "XOR": XOR,
    // "XOR Brute Force": XORBruteForce,
};


export default definitions;