// Date: Sun, 14 Jan 2024
// Second Author: Ryan Laf
// Description:
// License: AGPLv3
// Copyright (C) 2024 - Present, https://laftools.dev and https://codegen.cc

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
 *
 * @author n1474335 [n1474335@gmail.com]
 * @copyright Crown Copyright 2023
 * @license Apache-2.0
 */
import AvroToJSON from "../../operations/AvroToJSON.mjs";
import BSONDeserialise from "../../operations/BSONDeserialise.mjs";
import BSONSerialise from "../../operations/BSONSerialise.mjs";
import CBORDecode from "../../operations/CBORDecode.mjs";
import CBOREncode from "../../operations/CBOREncode.mjs";
import ParseObjectIDTimestamp from "../../operations/ParseObjectIDTimestamp.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Serialise = {
  "Avro to JSON": AvroToJSON,
  "BSON deserialise": BSONDeserialise,
  "BSON serialise": BSONSerialise,
  "CBOR Decode": CBORDecode,
  "CBOR Encode": CBOREncode,
  "Parse ObjectID timestamp": ParseObjectIDTimestamp,
};

export default OpModules;
