// Date: Sun, 14 Jan 2024
// Second Author: Ryan Laf
// Description:
// License: AGPLv3
// Copyright (C) 2024 - Present, https://laftools.dev and https://codegen.cc

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
 *
 * @author n1474335 [n1474335@gmail.com]
 * @copyright Crown Copyright 2023
 * @license Apache-2.0
 */
import ExtractDates from "../../operations/ExtractDates.mjs";
import ExtractDomains from "../../operations/ExtractDomains.mjs";
import ExtractEmailAddresses from "../../operations/ExtractEmailAddresses.mjs";
import ExtractFilePaths from "../../operations/ExtractFilePaths.mjs";
import ExtractIPAddresses from "../../operations/ExtractIPAddresses.mjs";
import ExtractMACAddresses from "../../operations/ExtractMACAddresses.mjs";
import ExtractURLs from "../../operations/ExtractURLs.mjs";
import Filter from "../../operations/Filter.mjs";
import FindReplace from "../../operations/FindReplace.mjs";
import Register from "../../operations/Register.mjs";
import RegularExpression from "../../operations/RegularExpression.mjs";
import Strings from "../../operations/Strings.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Regex = {
  "Extract dates": ExtractDates,
  "Extract domains": ExtractDomains,
  "Extract email addresses": ExtractEmailAddresses,
  "Extract file paths": ExtractFilePaths,
  "Extract IP addresses": ExtractIPAddresses,
  "Extract MAC addresses": ExtractMACAddresses,
  "Extract URLs": ExtractURLs,
  Filter: Filter,
  "Find / Replace": FindReplace,
  Register: Register,
  "Regular expression": RegularExpression,
  Strings: Strings,
};

export default OpModules;
