// Date: Sun, 14 Jan 2024
// Second Author: Ryan Laf
// Description:
// License: AGPLv3
// Copyright (C) 2024 - Present, https://laftools.dev and https://codegen.cc

/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
 *
 * @author n1474335 [n1474335@gmail.com]
 * @copyright Crown Copyright 2023
 * @license Apache-2.0
 */
import HexToObjectIdentifier from "../../operations/HexToObjectIdentifier.mjs";
import HexToPEM from "../../operations/HexToPEM.mjs";
import ObjectIdentifierToHex from "../../operations/ObjectIdentifierToHex.mjs";
import ParseASN1HexString from "../../operations/ParseASN1HexString.mjs";
import ParseX509Certificate from "../../operations/ParseX509Certificate.mjs";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.PublicKey = {
  "Hex to Object Identifier": HexToObjectIdentifier,
  "Hex to PEM": HexToPEM,
  "Object Identifier to Hex": ObjectIdentifierToHex,
  "Parse ASN.1 hex string": ParseASN1HexString,
  "Parse X.509 certificate": ParseX509Certificate,
};

export default OpModules;
