
export const SOURCETYPE_GIFT_CARD = 'GIFT_CARD'
export const SOURCETYPE_USER_PAYMENT = 'USER_PAYMENT'
export const SOURCETYPE_EARLIER_USER_SPECIAL_OFFER = 'EARLIER_USER_SPECIAL_OFFER'
export const SOURCETYPE_LIFELONG_PREMIUM_USER = 'LIFELONG_PREMIUM_USER'

export const PURCHASE_TYPE_PREMIUM_MEMBERSHIP = 'PREMIUM_MEMBERSHIP'