export default function GetAppInfo() {
    return {
        name: '秒达工具箱',
        // link: 'MDGJX.com',
        link: 'laftools.cn',
        // link: 'zdgjx.com',
        // name: '秒达工具箱',
        // name: '途方工具箱',
        // name: '途方工具箱',
        // name: 'ToJSON工具箱',
        // link: '1sGET.com',
        // link: 'soyaml.com',
        // link: 'json9.com',
        // link: 'md5u.com',
        // link: 'soyaml.com',
        // link: 'sogcc.com',
        // link: 'sogcc.com',
        // link: 'sobbc.com',
        // link: 'sobbx.com',
        // link: 'sobxz.com',
        // link: 'somdx.com',
        // link: 'tofunc.com',
        // link: '1mda.com',
        // link: 'solinux.com',
        // link: '1sGET.com',
        // link: 'tofunc.com',
        githubRepo: 'https://github.com/work7z/MDGJX',
        needDoBeiAn: true
    }
}